dist: xenial
language: python
python:
  - "3.8"
  # command to install dependencies

before_install:
- sudo apt-get update -y

install:
  - sudo apt-get install wget -y
# command to run tests
script:
  - echo HELLO_WORLD
  - pwd
  - ls
  
  
  
  
  
