dist: xenial
language: python
python:
  - "3.8"
  # command to install dependencies

before_install:
- sudo apt-get update -y

install:
  - pip install -r requirements.txt
  - apt-get wget 
# command to run tests
script:
  - echo HELLO_WORLD
  
  
  
  
  
