# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: 
  vmImage: 'ubuntu-latest'

stages:

  - stage: deploy
    jobs:
      - job: deploying
        displayName: deploying to webserver
   #     pool:
    #      vmImage: 'ubuntu-latest'
        steps:
          - bash: |
              pwd
              ls
 
  - stage: Report_Generation

    jobs:
      - job: Report
        displayName: Generating Report
     #   pool:
      #    vmImage: 'ubuntu-latest'
        steps:
          - bash : |
              sudo apt-get install default-jre
              sudo apt-get install nodejs
              sudo apt-get install npm
              sudo npm install -g n
              sudo npm install -g allure-commandline
              allure generate $(System.DefaultWorkingDirectory)/allure-results --clean -o $(System.DefaultWorkingDirectory)/allure-results
              pwd
              ls
          - publish: $(System.DefaultWorkingDirectory)

  - stage: Notification
    jobs:
      - job : Notifying
        displayName: Sending notification
       # pool:
        #  vmImage: 'ubuntu-latest'
        steps:
          - bash: |
              sudo apt install mailutils
              sudo systemctl restart postfix
              sudo systemctl status postfix
              echo "Find the ci/cd report in attachment" | mail -s "Pipeline Notification" vinaysharma2591@gmail.com -A $(System.DefaultWorkingDirectory)/allure-results/index.html
             
              

