
# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- vinay

pool: 
  vmImage: 'ubuntu-latest'

stages:

  - stage: Build
    jobs:
      - job: Build
        displayName: Installing dependencies
        steps:
          - bash: |
              pwd
              ls
 
  - stage: Report_Generation

    jobs:
      - job: Report
        displayName: Generating Report
        steps:
          - bash : |
              sudo apt-get install default-jre
              sudo apt-get install nodejs
              sudo apt-get install npm
              sudo npm install -g n
              sudo npm install -g allure-commandline
              allure generate $(System.DefaultWorkingDirectory)/allure-results --clean -o $(System.DefaultWorkingDirectory)/allure-results
      
          - publish: $(System.DefaultWorkingDirectory)

          - bash: |
              sudo apt install mailutils
              sudo systemctl restart postfix
              sudo systemctl status postfix
              sudo echo "Find the ci/cd report in attachment" | mail -s "Pipeline Notification" vinkumar@qasource.com -A $(System.DefaultWorkingDirectory)/allure-results/index.html
              sudo mailq
              
          - bash: |
              curl -X POST -H 'Content-type: application/json' --data '{"text":"build complete"}' https://hooks.slack.com/services/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
  - stage: Deploy

    jobs:
      - job: Deploying_Artifacts
        displayName: Copying data to servers
        steps:
        - bash: |
            sudo sh scripts/driver.sh
      #        sudo sshpass -p "vinay@123" rsync -rvz -e 'ssh -o StrictHostKeyChecking=no -p 22' --progress /home/vsts/work/1/s/hello.txt root@13.233.108.180:/azure
       #       sudo sshpass -p 'vinay@123' ssh -o StrictHostKeyChecking=no root@13.233.108.180 "cd /home/vinay && ansible-playbook tomcat.yml"
